# Generated by Django 5.2.8 on 2025-11-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Identificador na URL (ex: acai-puro)', unique=True)),
                ('cor_primaria', models.CharField(default='#6b21a8', help_text='Cor Hex (ex: #6b21a8)', max_length=7)),
                ('cor_secundaria', models.CharField(default='#4c1d95', max_length=7)),
                ('telefone_whatsapp', models.CharField(help_text='5521999999999', max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.loja'),
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.loja'),
        ),
    ]
