# Generated by Django 5.2.8 on 2025-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loja_dono_alter_loja_cor_primaria_alter_loja_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='descricao',
            field=models.TextField(blank=True, help_text='Uma frase curta sobre a loja', null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço completo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='instagram',
            field=models.CharField(blank=True, help_text='Ex: @lojadogui', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loja',
            name='slug',
            field=models.SlugField(help_text='Identificador na URL', unique=True),
        ),
    ]
